baseURL = 'https://qianhualiao.github.io'
languageCode = "en-us"
title = 'Cynwaa is here'
theme = "hugo-theme-cleanwhite"

[params]
  header_image = "img/Axamer-Lizum.jpeg"
  SEOTitle = "廖倩华的博客 | QianhuaLiao Blog"
  keyword = "Cynwaa, Blog, 博客, 个人网站, 成长，学习"
  slogan = "人生就是不停地折腾"

# Sidebar settings
  sidebar_about_description = "Tech Consultant, Adventurer, Lifelong Learner"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  [[params.addtional_menus]]
  title = "ALL POSTS"
  Href = "/posts/"
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/content/about/"