baseURL = "https://qianhualiao.github.io"
languageCode = "en-us"
title = "Qianhua's Notes"
theme = "hugo-theme-cleanwhite"
# Enable comments by entering your Disqus shortname
# disqusShortname = "Qianhua"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]




[params]
  header_image = "img/Axamer-Lizum.jpeg"
  SEOTitle = "廖倩华的博客 | QianhuaLiao Blog"
  keyword = "Cynwaa, Blog, 博客, 个人网站, 成长，学习"
  slogan = "人生就是不停地折腾"

# Sidebar settings
  sidebar_about_description = "Tech Consultant, Adventurer, Lifelong Learner"
  sidebar_avatar = "img/Qianhua-Liao.jpeg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  [[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.addtional_menus]]
  title =  "NOTES"
  href =  "/notes/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"

  [params.social]
  #rss            = true 
  email          = "qianhua.liao@hotmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/qianhualiao"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/QianhuaLiao"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"


  [outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

  [params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"] 

  ## 配置 utteranc评论,教程参考 https://utteranc.es/
  [params.utteranc]
  enable = true
  repo = "QianhuaLiao/hugoblogcomment"
  issueTerm = "pathname"
  theme = "github-light"

  [markup]
    [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
    [markup.highlight]
    style = "dracula"