baseURL = 'https://QianhuaLiao.github.io/blog/'
languageCode = "en"
title = 'Cynwaa is here'
theme = "hugo-theme-cleanwhite"

[params]
  SEOTitle = "廖倩华的博客 | QianhuaLiao Blog"
  keyword = "Cynwaa, Blog, 博客, 个人网站, 成长，学习"
  slogan = "人生就是不停地折腾"
